class S1{
public static void main (String[] args)
{
String news="contrary to popular perception";
System.out.println(news);
String name="sneha";
System.out.println(name);
String add="kachinaktte shivamogga";
System.out.println(add);
String age="twenty";
System.out.println(age);
String sister="sonu";
System.out.println(sister);
String mother="padmavathi";
System.out.println(mother);
String father="umesh";
System.out.println(father);

String grandmother="manjamma";
System.out.println(grandmother);

String edu="engineering";
System.out.println(edu);
String nice="good girl";
System.out.println(nice);
String job="searching job";
System.out.println(job);
String hobby="watering the plants";
System.out.println(hobby);
String hobb="taking tution";
System.out.println(hobb);
String sgoal="got a job";
System.out.println(sgoal);
String ertt="hfayawurischb";
System.out.println(ertt);
String present="in depression";
System.out.println(present);
String future="dont know";
System.out.println(future);
String cha="selent";

System.out.println(cha);
String ch1="innocent";
System.out.println(ch1);
String ch2="happy face";
System.out.println(ch2);
String ch9="genune person";
System.out.println(ch9);
String ch3="honesty";
System.out.println(ch3);
String ch4="kind hearted";
System.out.println(ch4);
String behaviour="good girl";
System.out.println(behaviour);
String interest="sleeping";
System.out.println(interest);
String trusty="trusty person";
System.out.println(trusty);
String beng="cold weather";
System.out.println(beng);
String newsb="In-built navigation data from car used by former airline crew member serves as evidence in murder of colleague in Udupi";
System.out.println(newsb);
String kar="Karnataka HC quashes Centre’s order cancelling FCRA registration of Centre for Wildlife Studies";
System.out.println(kar);
String stuck="The Karnataka High Court has struck ";
System.out.println(stuck);
String cell="Ministry of Home Affairs cancelling the Foreign Contribution Regulation ";
System.out.println(cell);
String mobile="registration of the Centre for Wildlife Studies, a Bengaluru-based organisation focusing on wildlife";
System.out.println(mobile);
String nin="research and conservation. The order was passed on June 25 by a bench consisting of Justice M Nagaprasanna.";
System.out.println(nin);
String trust="Ullas Karanth, chief functionary of the trust";
String can="has got the Centre for Wildlife Studies registered";
System.out.println(can);
String etc="990 to promote wildlife study, conservation etc";
System.out.println(etc);

String belong="hange of bank account which was applied for, foreign";
System.out.println(belong);
String big=" contributions were also made. The same year, the Central Government";
System.out.println(big);
String sand="had issued a six-month suspension of the trust registration and a questionnaire, ";
System.out.println(sand);
String cont="which Karanth’s counsel contended was not received.";
System.out.println(cont);
String june="In December that year, the trust sent a detailed reply ";
System.out.println(june);
String july="response to a show cause notice. In September 2023, an order was passed cancelling the FCRA registration.";
System.out.println(july);
String cannn="Karanth’s counsel argued that the order cancelling the registration";
System.out.println(can);
String cannaot="hi  how are you";
System.out.println(cannaot);
String jan="am fine";
System.out.println(jan);
String feb="waht about you";
System.out.println(feb);
String march="wattsapp ";
System.out.println(march);
String april ="how is going your work";
System.out.println(april);
String may="dont idea";
System.out.println(may);
String aug="how is ur life";
System.out.println(aug);

String sept="go with the flow";
System.out.println(sept);
String oct="my birthsay";
System.out.println(oct);
String nov="my sister birthday";
System.out.println(nov);
String dec="ristmas";
System.out.println(dec);

String how="how aare youuu";
System.out.println(how);

String love="loves everything";
System.out.println(love);
String life="be happy";
System.out.println(life);
String stress="dont take stress";
System.out.println(stress);
String th="you are just 20";
System.out.println(th);
String s1="why think too much";
System.out.println(s1);
String s2="dont think ";
System.out.println(s2);
String s3="all for good";
System.out.println(s3);
String s4="have patience";
System.out.println(s4);
System.out.println(s3);
String s5="good day is come";
System.out.println(s5);
String s6="all is well";
System.out.println(s6);
String s7="pls read everyday";
System.out.println(s7);
String s8="your future";
System.out.println(s8);
String s9="depends onu";
System.out.println(s9);
String s10="so pls think ";
System.out.println(s10);
String s11="about yoer future";
System.out.println(s11);
String end="byeee hava a nice day";
System.out.println(end);

}}